### ISSUE TITLE
Dont sent brightness value if Autobrightness is on when RGB changes

### ISSUE THREAD

**Issue by jellewie** [jellewie/Arduino-Smart-light#21]
**Issue:**
Sending the brightness value will turn AutoBrightness off

**Solution**
So with 'Auto brightness == true' do not send the brightness  value (L) together with RGB if the user changes the RGB sliders,
Do send the brightness value when the user changes the brightness itself.

if (RGB sliders adjusted) AND (Autobrightness) 
  only send RGB 
else
  Send RGBL

**Comment by jespertheend** [comment]
fixed in e4fdc7c
