### ISSUE TITLE
Toast message should be on top of settings window

### ISSUE THREAD

**Issue by jellewie** [jellewie/Arduino-Smart-light#23]
The toast message is now below the settings window

![image showing the toast message below the settings window](https://user-images.githubusercontent.com/1545223/90112793-bf032d00-dd50-11ea-822f-339b805ea99f.png)

# Link to source
[Arduino code](https://github.com/jellewie/Arduino-Smart-light/blob/master/Arduino/handler.ino#L177)
[HTML version](https://github.com/jellewie/Arduino-Smart-light/blob/master/Website/Index.html)

**Comment by jespertheend** [comment]
Fixed in aee752f
